# Generated by Django 2.2.6 on 2019-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('pno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=15)),
                ('cpwd', models.CharField(max_length=15)),
            ],
        ),
    ]
