# Generated by Django 2.2.6 on 2019-10-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg',
            new_name='Register',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='pno',
            new_name='phno',
        ),
    ]
